In [2]:
#numpy stands for numerical python.
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns 

a = np.array([1,2,3,4,5,6])
print(type(a))

<class 'numpy.ndarray'>


In [6]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [8]:
from scipy import constants
print(constants.c)
 
print(constants.h)

print(constants.N_A)

299792458.0
6.62607004e-34
6.022140857e+23


In [11]:
import pandas as pd

#numpy array is fast , convenient , and less memory.

a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [12]:
import time
import sys
c = np.arange(1000)
print(c.size*c.itemsize)

4000


In [18]:
c = np.arange(1000)
c.size*c.itemsize

4000

In [28]:
#with float64 data type
a = np.array([[1,2],[3,4],[5,6]] , dtype = np.float64)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [24]:
a.ndim

2

In [25]:
a.shape   


(3, 2)

In [26]:
a.itemsize

4

In [40]:
# with complex data type
a = np.array([[1,2],[3,4],[5,6]] , dtype = np.complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [41]:
a.itemsize


16

In [42]:
a.ndim

2

In [43]:
a.shape

(3, 2)

In [46]:
np.zeros((3,4))       # stroing all 0 elements.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [51]:
print('Concatenation Example')      # adding numpy array
print(np.char.add(['Hello ','Hi '],['Nikhil','Tom']))

Concatenation Example
['Hello Nikhil' 'Hi Tom']


In [55]:
print(np.char.multiply(' HELLO ',3))        #multiplying in numpy

 hello  hello  hello 


In [67]:
print(np.char.center('hello',40,fillchar = '-')) #printing fill character 

-----------------hello------------------


In [76]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], dtype =  np.float64)
b

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [72]:
b.shape

(3, 3)

In [73]:
b.itemsize

8

In [77]:
b.reshape(4,3)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [78]:
print(np.char.center('hello',20,fillchar=','))     #used to fill symbols in a text.

,,,,,,,hello,,,,,,,,


In [79]:
print(np.char.capitalize('hello world'))      #  used to make the string uppercase.

Hello world


In [80]:
print(np.char.title('how are you doing'))         # title is also used to capitalize.

How Are You Doing


In [82]:
print(np.char.upper('hello world'))              # using upper and lower function.
print(np.char.lower('Hello World'))

HELLO WORLD
hello world


In [83]:
print(np.char.split('are you coming to the party'))       #using split function.

['are', 'you', 'coming', 'to', 'the', 'party']


In [84]:
print(np.char.splitlines('hello\nnikhil\nhow are you'))      #splitness used to break the lines.


['hello', 'nikhil', 'how are you']


In [86]:
print(np.char.strip(['nikhil','neha','nimishene'],'n'))    #remove element from back and front.

['ikhil' 'eha' 'imishene']


In [87]:
print(np.char.join([':',','],['dmy','ymd']))                   # join two numpy arrays.

['d:m:y' 'y,m,d']


In [90]:
print(np.char.replace('He is a good dancer','He','Nikhil'))


Nikhil is a good dancer
